paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: ryok
google_analytics: ryok
title: tech-mba 学び書き殴りブログ

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: ryok

description: MBA取得中のIT技術者（インフラ系, Python, DNN等）が学んだ内容を体系的にまとめるweb。
author:
  name: ryok
  email: ry1537+tm@gmail.com
  github: ryo-kudo
  twitter: kepler_31
  # pinterest: none
  # linkedin: none
  bio: MBA(US), IT engineer
  # email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH: "/tech-mba"

plugins:
  - jekyll-paginate
